import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@/components";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>QuickCV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homeWrapper}>
        <h1>Welcome to QuickCV</h1>
        <div className={styles.homeActions}>
          <Button onClick={() => router.push("/initiate")}>Initiate</Button>
        </div>
      </main>
    </>
  );
}
