import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button } from "@/components";
import { useRouter } from "next/router";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import { LandingLayout } from "@/layouts/landing.layout";

export const Home: NextPageWithLayout = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>QuickCV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homeWrapper}>
        <section className={styles.welcomeSection}>
          <h2 className={styles.welcomeSectionTitle}>Impress in Seconds!</h2>
          <p className={styles.welcomeSectionSubTitle}>
            Discover your dream job with a resume crafted in minutes.
          </p>
          <Button onClick={() => router.push("/initiate")}>
            let your success story unfold.
          </Button>
        </section>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <LandingLayout>{page}</LandingLayout>;
};

export default Home;
